observeinc/terraform-provider-observe

observe/data_source_app_test.go
observe/resource_app_test.go

The tests related to apps were getting into an infinite loop when deleting the apps on cleanup when the app was stuck in deleting state for some reason. Commenting out these tests for now to unblock the acceptance tests.

fix: broken acceptance tests

---

GNUmakefile
client/internal/meta/operation/dataset.graphql
client/internal/meta/operation/poller.graphql
client/internal/meta/schema/base.graphql
client/internal/meta/schema/dataset.graphql
client/internal/meta/schema/poller.graphql
client/meta/dataset.go
client/meta/genqlient.generated.go

This commit filters deprecated fields, as marked by the @eol directive, from the client schema, adjusting the provider code as we go.

fix: filter EOL fields from schema

---

.goreleaser.yml

Something has changed in the Go linker and/or the repository, and we must now specify the fully qualified symbol to have it properly overwrite it with the release tag.

fix: UserAgent in release builds

---

docs/resources/monitor_v2.md
docs/resources/monitor_v2_action.md
examples/resources/observe_monitor_v2/import.sh
examples/resources/observe_monitor_v2_action/import.sh
observe/resource_monitor_v2.go
observe/resource_monitor_v2_action.go

Trying to run `terraform import` for a monitor_v2 resource resulted in the following error:
```
Error: resource observe_monitor_v2 doesn't support import
```
Turns out the `Importer` function needs to be implemented, and in this case I believe we can just use `ImportStatePassthroughContext` based on my understanding of the [docs](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/import)

Fix: support importing monitor_v2 and monitor_v2_action resources

---

docs/data-sources/monitor_v2.md
docs/resources/monitor_v2.md
observe/descriptions/monitorv2.yaml
observe/resource_monitor_v2.go

The GraphQL currently returns null for the `scheduling` field by default (if the user hasn't modified it), resulting in the exported terraform missing the required `scheduling` block.
Talked to @obs-gh-andrewlee and it looks like this is expected, with the scheduling defaulting to `transform` if it's not provided.

fix: make monitor_v2 scheduling block optional

---

observe/data_source_monitor_v2_test.go
observe/resource_monitor_v2_action_test.go
observe/resource_monitor_v2_test.go

Upstream has changed the acceptable resource definition, so we are temporarily disabling the tests until we can fix the resource definitions.

Disable failing monitorv2 tests

---

client/meta/helpers.go
observe/resource_dataset_outbound_share.go
observe/resource_datastream.go
observe/resource_filedrop.go
observe/resource_monitor.go
observe/resource_monitor_action.go
observe/resource_monitor_action_attachment.go
observe/resource_rbac_group.go
observe/resource_rbac_group_member.go
observe/resource_rbac_statement.go
observe/resource_snowflake_outbound_share.go

Updated the following resources to properly handle NOT_FOUND responses from the upstream:
- `dataset_outbound_share`
- `datastream`
- `filedrop`
- `monitor`
- `monitor_action`
- `rbac_group`
- `rbac_group_member`
- `rbac_statement`
- `snowflake_outbound_share`

Update Terraform state for NOT_FOUND (1/n)

---

docs/data-sources/monitor_v2.md
docs/resources/monitor_v2.md
observe/data_source_monitor_v2.go
observe/data_source_monitor_v2_test.go
observe/resource_monitor_v2.go
observe/resource_monitor_v2_action_test.go
observe/resource_monitor_v2_test.go

This feature had been moved upstream and no longer exists in this resource.

Remove schedule block from monitorv2

---

observe/resource_monitor_v2.go

Small typo that resulted in putting the data in the `path` instead of the index

fix: bug with encoding path for groupings

---

client/api.go
observe/resource_app.go
observe/resource_app_datasource.go
observe/resource_board.go
observe/resource_bookmark.go
observe/resource_bookmark_group.go
observe/resource_channel.go
observe/resource_channel_action.go
observe/resource_dashboard_link.go
observe/resource_dataset.go
observe/resource_datastream_token.go
observe/resource_default_dashboard.go
observe/resource_folder.go
observe/resource_layered_setting_record.go
observe/resource_link.go
observe/resource_poller.go
observe/resource_preferred_path.go
observe/resource_source_dataset.go
observe/resource_worksheet.go

This should prevent terraform state divergence for the included resources when the resource is deleted out of band.

Add NOT_FOUND error handling to resources [2/n]

---

client/internal/meta/operation/dataset.graphql
client/internal/meta/schema/dataset.graphql
client/meta/genqlient.generated.go
docs/data-sources/dataset.md
docs/resources/dataset.md
observe/data_source_dataset.go
observe/descriptions/dataset.yaml
observe/resource_dataset.go
observe/resource_dataset_test.go

Tested creating dataset with `data_table_view_state` specified, updating it, and going through the equivalent of what Export Terraform does.

feat: support dataTableViewState field for datasets

---

client/api.go
client/binding/binding.go
client/binding/binding_test.go
client/binding/types.go
client/binding/types_test.go
client/config.go
client/internal/meta/operation/dataset.graphql
client/internal/meta/operation/user.graphql
client/internal/meta/operation/worksheet.graphql
client/meta/dataset.go
client/meta/genqlient.generated.go
client/meta/user.go
client/meta/worksheet.go
docs/index.md
observe/data_source_dashboard.go
observe/data_source_dashboard_test.go
observe/provider.go
observe/resource_dashboard.go

This is an internal use options that allows id references to be collected in a unified location in the resulting datasource read schema for further postprocessing.

Add binding export functionality to dashboards

---

client/internal/meta/operation/dataset.graphql
client/meta/genqlient.generated.go
docs/data-sources/dataset.md
observe/data_source_dataset.go
observe/data_source_dataset_test.go
observe/descriptions/dataset.yaml

This should be exposed for downstream consumption so users can obtain the set of correlation tags currently attached to their datasets.

feat: Add correlation tags to dataset datasource schema

---

client/internal/meta/operation/dataset.graphql
client/internal/meta/schema/dataset.graphql
client/meta/genqlient.generated.go
client/meta/helpers.go
docs/data-sources/dataset.md
docs/resources/dataset.md
observe/data_source_dataset.go
observe/descriptions/dataset.yaml
observe/resource_dataset.go
observe/resource_dataset_test.go

Should not be merged until GQL support hits all clusters (OB-36860).

OB-37347: Update terraform API to handle acceleration disabled source

---

client/api.go
client/internal/meta/schema/dataset.graphql
client/meta/dataset.go
client/meta/genqlient.generated.go
client/meta/helpers.go
docs/data-sources/dataset.md
docs/resources/dataset.md
examples/data-sources/observe_dataset/data-source.tf
observe/descriptions/dataset.yaml
observe/helpers.go
observe/resource_dataset.go
observe/resource_dataset_test.go

Expose `saveDataset`'s `rematerialization_mode` to `resource_dataset` in Terraform. Must be merged after 10/30 prod release because GraphQL API not released yet. Tested and verified with `testbox`.

feat: Allow edit-forward of Terraform-managed datasets

---

observe/resource_dataset_test.go

It is now illegal to convert between materialized datasets and view datasets, so we must update the test accordingly.

Fix failing dataset tests

---

client/internal/meta/operation/dataset.graphql
client/internal/meta/schema/dataset.graphql
client/meta/dataset.go
client/meta/genqlient.generated.go

This field is the proper one to use to determine when the last user modifications were made to a dataset which also excludes system modifications and is required to properly support an upcoming release

Update dataset version field to use lastSaved instead of updatedDate

---

observe/resource_monitor_v2_action.go
observe/resource_monitor_v2_action_test.go

This should default to an empty string, not a JSON null for the UI to render correctly.

Fix Monitor V2 Email Shared Action Body

---

client/meta/dataset.go
observe/resource_dataset.go
observe/resource_dataset_test.go

Currently, for any existing dataset resources, the value for `rematerialization_mode` in the tfstate file is `""` since unlike for other fields that are set in `resourceDatasetRead`, `rematerialization_mode` isn't an actual property of datasets and there's no value for it returned by the API. This results in an unnecessary diff of `"" -> "rematerialize"` even though `rematerialize` is the default value.
To avoid this, I updated `resourceDatasetRead` to set `rematerialization_mode` to `rematerialize` if there's not already a value for it.

fix: prevent unnecessary diff for rematerialization_mode

---

client/internal/meta/operation/monitorv2.graphql

The MonitorV2ActionInput type is used by multiple mutations, only one of which includes the genqlient directive to include `omitempty` in the generated Go type. This results in the generated type sometimes including omitempty and sometimes not, depending on the order in which the GraphQL files are processed.

fix: remove omitempty directive from MonitorV2ActionInput.inline to prevent nondeterministic generation

---

observe/resource_rbac_group_member.go
observe/resource_rbac_group_member_test.go
observe/resource_source_dataset_test.go

- In RBAC v2, groups can no longer be members of other groups
- In RBAC v2, the description for rbac_group_member is ignored
- Source dataset field type "any" is now called "variant"

fix: update tests

---

docs/data-sources/monitor_v2.md
observe/data_source_monitor_v2.go

Currently, when exporting a TypeList with Elem: schema.Resource, it gets exported as a list of objects (using square brackets) instead of blocks, which is invalid.
Turns out the `terraform show` command used by our export implementation will have this behavior when `Computed: true` is used without either `Optional: true` or `Required: true`. This is likely because the block format only makes sense when it's possible to use the field as an input. For purely computed fields, we would only reference the data and the list format is equivalent in that case.
Added `Optional:true` to all relevant fields, though it is not actually valid to provide these fields as input when querying and will be ignored.

fix: ensure lists of objects are exported as blocks for monitor v2

---

observe/diff.go
observe/resource_rbac_group_member.go

With RBAC v2, the groupmember description field is ignored and we don't want unnecessary diffs. In RBAC v1, the description field is saved but not actually used or displayed anywhere, so it's safe to suppress.

fix: always diff suppress groupmember description

---

docs/resources/monitor_v2.md
observe/resource_http_post_test.go
observe/resource_monitor_v2.go
observe/resource_monitor_v2_test.go

1. DiffSuppressFunc set to diffSuppressTimeDuration for lookback_time. This is to ensure a null lookback_time doesn't trigger the resource to update (check: OB-40067).
2. value_duration Type set to schema.TypeString as the validateTimeDuration would panic when casting the type integer to a string.

Fix two bugs in the resource_monitor_v2

---

client/internal/meta/schema/monitorv2.graphql
client/meta/genqlient.generated.go

Nothing drastic here. It already uses the toSnake() to properly format/unformat. Just bringing over the new enums.

feat: Add IsNull and IsNotNull for MonitorV2 comparisons

---

docs/data-sources/board.md
docs/data-sources/dataset.md
docs/resources/board.md
docs/resources/channel.md
docs/resources/channel_action.md
docs/resources/dataset.md
docs/resources/grant.md
docs/resources/rbac_statement.md
docs/resources/resource_grants.md
observe/data_source_board.go
observe/descriptions/dataset.yaml
observe/descriptions/grant.yaml
observe/descriptions/resource_grants.yaml
observe/resource_board.go
observe/resource_channel.go
observe/resource_channel_action.go
observe/resource_rbac_statement.go

- Specifying a DeprecationMessage doesn't update the docs due to https://github.com/hashicorp/terraform-plugin-docs/issues/10, manually updated the description for all deprecated resources
- Deprecated observe_rbac_statement in favor of observe_grant for use with RBAC v2
- Removed "under development" note for `observe_grant` and `observe_resource_grants`
- Clarified that `dataTableViewState` is not intended to be configured by hand

docs: update deprecation messages

---

client/internal/meta/operation/user.graphql
client/meta/genqlient.generated.go
client/meta/user.go
observe/observe_sweeper_test.go

- only need to sweep role statements since resource statements are deleted when the resource is deleted
- rbac statements no longer support descriptions, so deleting all statements created by this user instead of matching by description

fix: sweeper for rbac statements

---

client/rest/referencetables.go
docs/data-sources/reference_table.md
docs/resources/reference_table.md
observe/data_source_reference_table.go
observe/descriptions/reference_table.yaml
observe/resource_reference_table.go
observe/resource_reference_table_test.go

Needed to use `data.GetRawConfig()` to work around a terraform limitation, see comment for details.

feat: add schema support for reference tables

---

docs/resources/dataset.md
observe/descriptions/dataset.yaml
observe/resource_dataset.go
observe/resource_dataset_test.go

Changing the behavior of "skip_rematerialization" to fail if skipping rematerialization is not possible may cause issues with apps in certain rare cases. Changed it back to the original behavior, and introduced new option "must_skip_rematerialization" for new behavior.

fix: keep original behavior for skip_rematerialization, introduce new must_skip_rematerialization

---

observe/resource_layered_setting_record_test.go

to avoid conflicting with concurrently running tests (can't have 2 rbac groups with the same name)

test: add random prefix to rbac group in layered setting test

---

observe/resource_link.go

Normally, when running terraform apply, it'll refresh the state first at which point if a link no longer exists, terraform will plan to re-create it automatically. However, in the case where the link does exist when refreshing the state, but then is deleted during the apply (e.g. due to the source dataset being updated), the update to the link then fails. We now will re-create the link if the update fails due to link not found.

fix: re-create links if not found during update

---

client/api.go
client/binding/binding.go
client/binding/binding_test.go
client/binding/types.go
client/binding/types_test.go
client/meta/monitorv2_action.go
docs/data-sources/monitor.md
docs/data-sources/monitor_v2.md
observe/data_source_dashboard.go
observe/data_source_dashboard_test.go
observe/data_source_monitor.go
observe/data_source_monitor_test.go
observe/data_source_monitor_v2.go
observe/data_source_monitor_v2_action.go
observe/data_source_monitor_v2_test.go
observe/descriptions/monitor.yaml
observe/descriptions/monitorv2.yaml
observe/resource_dashboard.go
observe/resource_monitor.go
observe/resource_monitor_v2.go

Similar to the existing approach for dashboards, generates "bindings" to a terraform local variable for each id found in the monitor definition to support cross-tenant exports. Unlike with dashboards, monitors don't have a `layout` field to insert these bindings into for later consumption, so instead added a new `_bindings` field to the data source to hold this information.
Broken into separate commits for ease of reviewing.

feat: support generating bindings for monitors

---

docs/resources/monitor_v2.md
examples/resources/observe_monitor_v2/resource.tf
observe/resource_monitor_v2.go
observe/resource_monitor_v2_test.go

- works around Terraform SDK limitation preventing replacing an inline action with a shared action from working, see comments for more details
- also add example for no_data_rules

fix: replacing monitor v2 inline action with shared action

---

client/meta/helpers.go
observe/helpers.go
observe/resource_monitor_v2.go
observe/resource_monitor_v2_test.go

While specifying `NoData` is invalid as the level for a rule (should use the separate `no_data_rules` block instead), it is valid as a level for an action. Added it to the list of alarm levels but excluded it from the validation for `rules`

fix: support NoData monitor v2 alarm level for actions

---

observe/resource_drop_filter.go

Currently causing a perpetual diff when an observe_dataset.oid is used (which includes the version) instead of using observe_datastream.dataset

fix[drop filter]: diff suppress oid version

---

main.go

The time zone "America/Chicago" failed validation on some devices, which i wasn't able to reproduce. My best guess is missing system time zone data.
See https://pkg.go.dev/time/tzdata

fix: embed timezone database for validation on systems without timezone data

---

client/rest/referencetables.go
client/rest/reports.go
client/rest/service_accounts.go

Mainly for looking up reference tables by label, to support spaces in the label. The IDs should generally be url safe already, but escaping them anyway for a better error message if we do somehow get a bad id.
Hopefully will get the generator set up soon after which this won't need to be manually dealt with anymore.

fix: properly escape URL parts for REST API queries

---

docs/data-sources/monitor_v2.md
docs/resources/monitor_v2.md
observe/data_source_monitor_v2.go
observe/descriptions/monitorv2.yaml
observe/resource_monitor_v2.go

This is a small change to the documentation informing of the deprecation of the `interval` type monitors.

OB-49319: Document interval monitor deprecation
